# Generated by Django 4.2.19 on 2025-03-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_custom_forms", "0002_alter_customformdocuments_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="customformpdftemplate",
            name="notes_placeholder",
            field=models.CharField(
                blank=True,
                default="Provide additional details if needed",
                help_text="Placeholder text for the notes field",
                max_length=255,
                null=True,
            ),
        ),
    ]
