# Generated by Django 4.2.20 on 2025-04-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_custom_forms", "0004_alter_customform_form_number"),
    ]

    def update_special_mapping_signature(apps, schema_editor):
        CustomFormSpecialMapping = apps.get_model("NEMO_custom_forms", "CustomFormSpecialMapping")
        CustomFormSpecialMapping.objects.filter(field_value="action_taken_by").update(
            field_value="action_taken_by_signature"
        )
        CustomFormSpecialMapping.objects.filter(field_value="action_taken_by_time").update(
            field_value="action_taken_by_time_signature"
        )

    def update_special_mapping_signature_reverse(apps, schema_editor):
        CustomFormSpecialMapping = apps.get_model("NEMO_custom_forms", "CustomFormSpecialMapping")
        CustomFormSpecialMapping.objects.filter(field_value="action_taken_by_signature").update(
            field_value="action_taken_by"
        )
        CustomFormSpecialMapping.objects.filter(field_value="action_taken_by_time_signature").update(
            field_value="action_taken_by_time"
        )

    operations = [migrations.RunPython(update_special_mapping_signature, update_special_mapping_signature_reverse)]
