# Generated by Django 4.2.20 on 2025-05-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_custom_forms", "0005_alter_custom_mapping_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="customformactionrecord",
            name="action_name",
            field=models.CharField(blank=True, help_text="The optional action name", max_length=100, null=True),
        ),
    ]
